// flow-typed signature: 121dd54af1a773656e97bb302bbc8858
// flow-typed version: <<STUB>>/atom-package-deps_v^4.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-package-deps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-package-deps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-package-deps/decls/atom' {
  declare module.exports: any;
}

declare module 'atom-package-deps/decls/jasmine' {
  declare module.exports: any;
}

declare module 'atom-package-deps/decls/package-deps' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/helpers' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/index' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/types' {
  declare module.exports: any;
}

declare module 'atom-package-deps/lib/view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-package-deps/decls/atom.js' {
  declare module.exports: $Exports<'atom-package-deps/decls/atom'>;
}
declare module 'atom-package-deps/decls/jasmine.js' {
  declare module.exports: $Exports<'atom-package-deps/decls/jasmine'>;
}
declare module 'atom-package-deps/decls/package-deps.js' {
  declare module.exports: $Exports<'atom-package-deps/decls/package-deps'>;
}
declare module 'atom-package-deps/lib/helpers.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/helpers'>;
}
declare module 'atom-package-deps/lib/index.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/index'>;
}
declare module 'atom-package-deps/lib/types.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/types'>;
}
declare module 'atom-package-deps/lib/view.js' {
  declare module.exports: $Exports<'atom-package-deps/lib/view'>;
}
