// flow-typed signature: 30ee019eac12a9f53c575766b2a28e14
// flow-typed version: <<STUB>>/jsonfile_v2.4.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jsonfile/index' {
  declare module.exports: $Exports<'jsonfile'>;
}
declare module 'jsonfile/index.js' {
  declare module.exports: $Exports<'jsonfile'>;
}
