// flow-typed signature: 4e0523921128c822573502d7e9eafb0f
// flow-typed version: <<STUB>>/react-elm-components_v1.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-elm-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-elm-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-elm-components/example/index' {
  declare module.exports: any;
}

declare module 'react-elm-components/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-elm-components/example/index.jsx' {
  declare module.exports: $Exports<'react-elm-components/example/index'>;
}
declare module 'react-elm-components/example/webpack.config.js' {
  declare module.exports: $Exports<'react-elm-components/example/webpack.config'>;
}
declare module 'react-elm-components/index' {
  declare module.exports: $Exports<'react-elm-components'>;
}
declare module 'react-elm-components/index.js' {
  declare module.exports: $Exports<'react-elm-components'>;
}
